apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: ghcr.io/yosemiteyss/pulsefeed-api:latest
          name: pf-api
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: pulsefeed-config
                  key: NODE_ENV
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: pulsefeed-config
                  key: DATABASE_URL
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: pulsefeed-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: pulsefeed-config
                  key: REDIS_PORT
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  name: pulsefeed-config
                  key: LOKI_URL