version: '3'

services:
  aggregate:
    build:
      context: ../pulsefeed-aggregate
    container_name: pf-aggregate
    depends_on:
      - postgres
      - redis
      - rabbitmq

  api:
    build:
      context: .
    container_name: pf-api
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  publish:
    build:
      context: ../pulsefeed-publish
    container_name: pf-publish
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres:16
    container_name: pf-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pulsefeed

  redis:
    image: redis:7
    container_name: pf-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit
    container_name: pf-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}