version: '3'

services:
  pulsefeed-aggregate:
    build:
      context: ../pulsefeed-aggregate
    ports:
      - "3124:3000"
    depends_on:
      - postgres
      - redis

  #  pulsefeed-api:
  #    build:
  #      context: .
  #    ports:
  #      - "3125:3000"
  #    depends_on:
  #      - postgres
  #      - redis

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pulsefeed

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
