version: '3'

services:
  aggregate:
    build:
      context: ../pulsefeed-aggregate
    container_name: pf-aggregate
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - redis

  api:
    build:
      context: .
    container_name: pf-api
    ports:
      - "3002:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: pf-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pulsefeed

  redis:
    image: redis:latest
    container_name: pf-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
