export const ONE_SECOND_IN_MS = 1000;
export const ONE_HOUR_IN_MS = 60 * 60 * 1000;
export const TWO_HOUR_IN_MS = 2 * ONE_HOUR_IN_MS;
export const THREE_HOUR_IN_MS = 3 * ONE_HOUR_IN_MS;
export const FOUR_HOUR_IN_MS = 4 * ONE_HOUR_IN_MS;
export const FIVE_HOUR_IN_MS = 5 * ONE_HOUR_IN_MS;
export const SIX_HOUR_IN_MS = 6 * ONE_HOUR_IN_MS;
export const TWELVE_HOUR_IN_MS = 12 * ONE_HOUR_IN_MS;
export const ONE_DAY_IN_MS = 24 * ONE_HOUR_IN_MS;
